name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    defaults: # Set default shell for all run steps in this job
      run:
        shell: powershell # Use Windows PowerShell

    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v3
        with:
          path: ui-service

      - name: Checkout K8s manifests repository
        uses: actions/checkout@v3
        with:
          repository: Luk-Up/k8s
          path: k8s

      - name: Debug Workspace and Paths
        run: |
          Write-Host "GitHub Workspace: ${{ github.workspace }}"
          Write-Host "Listing content of GitHub Workspace:"
          Get-ChildItem "${{ github.workspace }}" | ForEach-Object { Write-Host $_.FullName }
          $uiServiceCheckoutPath = Join-Path "${{ github.workspace }}" "ui-service"
          Write-Host "Expected ui-service checkout path: $uiServiceCheckoutPath"
          Write-Host "Listing content of ui-service checkout:"
          Get-ChildItem $uiServiceCheckoutPath -ErrorAction SilentlyContinue | ForEach-Object { Write-Host $_.FullName }
          $k8sCheckoutPath = Join-Path "${{ github.workspace }}" "k8s"
          Write-Host "Expected k8s checkout path: $k8sCheckoutPath"
          Write-Host "Listing content of k8s checkout:"
          Get-ChildItem $k8sCheckoutPath -ErrorAction SilentlyContinue | ForEach-Object { Write-Host $_.FullName }

      - name: Build Docker Image
        working-directory: ${{ github.workspace }}\ui-service\ui-service # Windows paths
        run: |
          Write-Host "Current directory for Docker build: $((Get-Location).Path)"
          Get-ChildItem # Lists items in the current directory
          docker build -t ahmedthemagnificent/ui-service .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # Consider v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ahmedthemagnificent/ui-service
      
      - name: Apply Kubernetes Manifests
        working-directory: ${{ github.workspace }}\k8s\ui-service # Windows paths
        run: |
         Write-Host "Current directory for kubectl: $((Get-Location).Path)"
         Get-ChildItem # Lists items in the current directory
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml