name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v3
        with: # <-------------------- CORRECTED HERE
          # repository: Luk-Up/ui-service # Not strictly needed if this workflow lives in Luk-Up/ui-service
          path: ui-service      # Checkout ui-service repo into {{ github.workspace }}/ui-service-code

      - name: Checkout K8s manifests repository
        uses: actions/checkout@v3
        with:
          repository: Luk-Up/k8s      # Checkout the k8s repo from the Luk-Up org
          path: k8s      # Checkout k8s repo into {{ github.workspace }}/k8s-manifests
          # token: ${{ secrets.PAT_FOR_K8S_REPO }} # Add if needed for private repo or permission issues

      - name: Build Docker Image
        working-directory: ./ui-service/ui-service # Navigate into the checked-out ui-service code
        run: docker build -t ahmedthemagnificent/ui-service . # Assumes Dockerfile is at the root of ui-service-code

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ahmedthemagnificent/ui-service
      
      - name: Apply Kubernetes Manifests
        working-directory: ./k8s/ui-service 
        run: |
         echo "Current directory for kubectl: $(pwd)"
         echo "Listing files in current directory:"
         ls -la 
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml