name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    # Explicitly set the default shell for run steps if you want to be sure
    # or if you want to use bash on Windows via Git Bash or WSL.
    # defaults:
    #   run:
    #     shell: pwsh # or powershell

    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v3 # Consider v4
        with:
          path: ui-service # Content of Luk-Up/ui-service repo goes into {{ github.workspace }}/ui-service

      - name: Checkout K8s manifests repository
        uses: actions/checkout@v4 # Consider v4
        with:
          repository: Luk-Up/k8s
          path: k8s       # Content of Luk-Up/k8s repo goes into {{ github.workspace }}/k8s

      - name: Debug Workspace and Paths
        run: |
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "Listing content of GitHub Workspace:"
          Get-ChildItem "${{ github.workspace }}"
          echo "Expected ui-service checkout path: ${{ github.workspace }}\ui-service"
          echo "Listing content of ui-service checkout:"
          Get-ChildItem "${{ github.workspace }}\ui-service" -ErrorAction SilentlyContinue
          echo "Expected k8s checkout path: ${{ github.workspace }}\k8s"
          echo "Listing content of k8s checkout:"
          Get-ChildItem "${{ github.workspace }}\k8s" -ErrorAction SilentlyContinue
        shell: pwsh # Explicitly use PowerShell for these commands

      - name: Build Docker Image
        # Dockerfile is at: {{ github.workspace }}/ui-service/ui-service/Dockerfile
        working-directory: ${{ github.workspace }}/ui-service/ui-service 
        run: |
          echo "Current directory for Docker build: $(Get-Location)" # PowerShell way
          Get-ChildItem # PowerShell equivalent of ls -l
          docker build -t ahmedthemagnificent/ui-service .
        shell: pwsh

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # Consider v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ahmedthemagnificent/ui-service
        # shell: pwsh # Not strictly needed for docker command, but good for consistency
      
      - name: Apply Kubernetes Manifests
        # Manifests are at: {{ github.workspace }}/k8s/ui-service/
        working-directory: ${{ github.workspace }}/k8s/ui-service 
        run: |
         echo "Current directory for kubectl: $(Get-Location)" # PowerShell way
         Get-ChildItem # PowerShell equivalent of ls -l
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml
        shell: pwsh