name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v4
        with:
          path: ui-service
          
      - name: Checkout K8s manifests repository
        uses: actions/checkout@v4
        with:
          repository: Luk-Up/k8s
          path: k8s
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ui-service/ui-service
          push: true
          tags: |
            ahmedthemagnificent/ui-service:latest
            ahmedthemagnificent/ui-service:${{ github.sha }}
          
      - name: Apply Kubernetes Manifests
        working-directory: ./k8s/ui-service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml