name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v3
        with:
          path: ui-service

      - name: Checkout K8s manifests repository
        uses: actions/checkout@v4
        with:
          repository: Luk-Up/k8s
          path: k8s

      - name: Build Docker Image
        working-directory: ${{ github.workspace }}\ui-service\ui-service # Windows paths
        run: |
          docker build -t ahmedthemagnificent/ui-service .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Consider v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ahmedthemagnificent/ui-service
      
      - name: Apply Kubernetes Manifests
        working-directory: ${{ github.workspace }}\k8s\ui-service # Windows paths
        run: |
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml