name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v4  # Updated to v4 for better performance
        with:
          path: ui-service/ui-service
          
      - name: Checkout K8s manifests repository
        uses: actions/checkout@v4
        with:
          repository: Luk-Up/k8s
          path: k8s
          # token: ${{ secrets.PAT_FOR_K8S_REPO }} # Uncomment if needed for private repo
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            registry-mirror=https://index.docker.io/v1/
            
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io  # Explicitly specify Docker Hub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ui-service/ui-service  # Fixed: removed the nested path
          file: ./ui-service/Dockerfile  # Explicitly specify Dockerfile location
          push: true
          tags: |
            ahmedthemagnificent/ui-service:latest
            ahmedthemagnificent/ui-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Verify Docker Image
        run: |
          docker pull ahmedthemagnificent/ui-service:${{ github.sha }}
          docker images | grep ahmedthemagnificent/ui-service
          
      - name: Update Kubernetes Manifests (if needed)
        working-directory: ./k8s/ui-service
        run: |
          # Optional: Update image tag in deployment.yaml
          if [ -f deployment.yaml ]; then
            sed -i "s|ahmedthemagnificent/ui-service:.*|ahmedthemagnificent/ui-service:${{ github.sha }}|g" deployment.yaml
          fi
          
      - name: Apply Kubernetes Manifests
        working-directory: ./k8s/ui-service
        run: |
          echo "Current directory for kubectl: $(pwd)"
          echo "Listing files in current directory:"
          ls -la
          
          # Check if kubectl is available and configured
          kubectl version --client
          kubectl config current-context
          
          # Apply manifests with better error handling
          if [ -f deployment.yaml ]; then
            echo "Applying deployment.yaml..."
            kubectl apply -f deployment.yaml
          else
            echo "Warning: deployment.yaml not found"
          fi
          
          if [ -f service.yaml ]; then
            echo "Applying service.yaml..."
            kubectl apply -f service.yaml
          else
            echo "Warning: service.yaml not found"
          fi
          
          # Wait for deployment to be ready
          kubectl rollout status deployment/ui-service --timeout=300s