name: UI service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout UI Service code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Consider v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: ./ui-service 
          file: ./ui-service/Dockerfile
          tags: |
              ahmedthemagnificent/ui-service:latest
              ahmedthemagnificent/ui-service:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout K8s manifests repository
        uses: actions/checkout@v4
        with:
          repository: Luk-Up/k8s
          path: k8s

     
      - name: Apply Kubernetes Manifests
        working-directory: ${{ github.workspace }}\k8s\ui-service # Windows paths
        run: |
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml
         kubectl rollout restart deployment/ui-service